### ISSUE TITLE
Photovoltaic Model Parameters extraction

### ISSUE THREAD

**Issue by MohammedQaraad** [pvlib/pvmodules#12]
could you please send me python code

**Comment by kandersolar** [comment]
Hi @MohammedQaraad, this project doesn't have any ready-to-use code.  I think #11 has a starting point you could potentially use to build your own in the meantime.  Otherwise, you can use github's "watch" feature on this repository so that you get updates if/when complete code is added to this repository.

**Comment by cwhanse** [comment]
@MohammedQaraad you could look into pvlib-python's ivtools module, there are functions for determining parameters for diode models. For example, `pvlib.ivtools.sdm.fit_cec_sam` uses the PySAM package to get CEC model parameters.
